from pathlib import Path

from app.core.paths import CONFIG_DIR, DATA_LOG_DIR, PUSH_DIR, RESULT_DIR, RUN_DIR, SCHEDULE_DIR, TEMPLATE_DIR

MASTER_CONFIG_FILE = CONFIG_DIR / "master_config.json"
DEFAULT_TEMPLATE_FILE = TEMPLATE_DIR / "default.json"
BINARY_STATE_FILE = CONFIG_DIR / "binary_state.json"
SAMPLE_TASK_FILE = RUN_DIR / "sample-task.json"
SAMPLE_RESULT_FILE = RESULT_DIR / "sample-task.json"
SAMPLE_LOG_INDEX_FILE = DATA_LOG_DIR / "sample-task.json"
SAMPLE_PUSH_FILE = PUSH_DIR / "sample-push.json"
SAMPLE_SCHEDULE_FILE = SCHEDULE_DIR / "sample-schedule.json"

ALL_SAMPLE_FILES: list[Path] = [
    DEFAULT_TEMPLATE_FILE,
    SAMPLE_TASK_FILE,
    SAMPLE_RESULT_FILE,
    SAMPLE_LOG_INDEX_FILE,
    SAMPLE_PUSH_FILE,
    SAMPLE_SCHEDULE_FILE,
]
